package com.esta.workforce.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.esta.workforce.data.model.Language

data class AppStrings(
    // Auth
    val authTitle: String = "Esta Construction",
    val authSubtitle: String,
    val authUsername: String,
    val authPassword: String,
    val authLogin: String,
    val authError: String,
    val authInfo: String,
    // Common
    val all: String,
    val noData: String,
    val loading: String,
    val logout: String,
    val settings: String,
    val notifications: String,
    val cancel: String,
    val save: String,
    val confirm: String,
    val search: String,
    val refresh: String,
    // Tabs
    val tabDashboard: String,
    val tabBrigades: String,
    val tabAttendance: String,
    val tabOvertime: String,
    val tabApprovals: String,
    val tabReports: String,
    // Status
    val statusPending: String,
    val statusSeen: String,
    val statusApproved: String,
    val statusRejected: String,
    // Workers
    val workersPresent: String,
    val workersAbsent: String,
    val workersTotal: String,
    // Shifts
    val shiftDay: String,
    val shiftNight: String,
    val shiftNone: String,
    // Overtime
    val overtimeNewRequest: String,
    val overtimeSelectSiteChief: String,
    val overtimeWorkDate: String,
    val overtimeNote: String,
    val overtimeSelectWorkers: String,
    val overtimeSend: String,
    val overtimeBack: String,
    // Notifications
    val notifNoItems: String,
    val notifLateTitle: String,
    val notifMissingTitle: String,
    val notifAddNote: String,
    val notifNoteExists: String,
    val notifSaveNote: String,
    val notifNoteHint: String,
    val notifNoEntry: String,
    val notifNoExit: String,
    val notifWorkedFor: String,
    // Brigades
    val brigMyWorkers: String,
    val brigAddWorkers: String,
    val brigNoWorkers: String,
    val brigNoWorkersHint: String,
    val brigRelease: String,
    val brigReleaseConfirm: String,
    val brigAddDay: String,
    val brigAddNight: String,
    val brigAllAssigned: String,
    // Settings
    val settingsTheme: String,
    val settingsLanguage: String,
    val settingsDark: String,
    val settingsLight: String,
    val settingsObject: String,
    val settingsSite: String,
    val settingsRole: String,
)

val TkStrings = AppStrings(
    authSubtitle = "Is guyjini dolandyrys",
    authUsername = "Ulanyjy ady",
    authPassword = "Parol",
    authLogin = "Giris",
    authError = "Nadogry maglumat",
    authInfo = "Ulanyjy ady we paroly Admin panelden berin",
    all = "Hemmesi",
    noData = "Maglumat yok",
    loading = "Yuklenyyar...",
    logout = "Cykys",
    settings = "Sazlamalar",
    notifications = "Habarlar",
    cancel = "Yatyr",
    save = "Sakla",
    confirm = "Tassykla",
    search = "Gozle...",
    refresh = "Tazele",
    tabDashboard = "Dolandyrys",
    tabBrigades = "Brigadalar",
    tabAttendance = "Gatnaşyk",
    tabOvertime = "Gosmaça",
    tabApprovals = "Tassyklamak",
    tabReports = "Hasabatlar",
    statusPending = "Garaşylýar",
    statusSeen = "Goruldi",
    statusApproved = "Tassyklandy",
    statusRejected = "Ret edildi",
    workersPresent = "İşde bar",
    workersAbsent = "Yok",
    workersTotal = "Jemi işçi",
    shiftDay = "Gundiz",
    shiftNight = "Gije",
    shiftNone = "Şift yok",
    overtimeNewRequest = "+ Täze sorag",
    overtimeSelectSiteChief = "Site Chief *",
    overtimeWorkDate = "İş senesi",
    overtimeNote = "Sebäp (islege görä)",
    overtimeSelectWorkers = "İşçi saýla",
    overtimeSend = "İber",
    overtimeBack = "← Yzyna",
    notifNoItems = "Bildiriş ýok",
    notifLateTitle = "işçi işe gelmedi",
    notifMissingTitle = "işçi çykyş belgisi ýok",
    notifAddNote = "Sebäp ýaz",
    notifNoteExists = "Sebäp bar",
    notifSaveNote = "Ýatla",
    notifNoteHint = "Meselem: kart ýitirdi, saglyk ýagdaýy...",
    notifNoEntry = "Giriş ýok",
    notifNoExit = "Çykyş ýok",
    notifWorkedFor = "işde",
    brigMyWorkers = "İşçilerim",
    brigAddWorkers = "İşçi goş",
    brigNoWorkers = "İşçi ýok",
    brigNoWorkersHint = "İşçi goş bölümünden işçileri öz sanawyňyza goşuň.",
    brigRelease = "İşçini aýyr",
    brigReleaseConfirm = "sanawyňyzdan aýrylsyn my?",
    brigAddDay = "Gündiz goş",
    brigAddNight = "Gije goş",
    brigAllAssigned = "Ähli işçiler birikdirilen",
    settingsTheme = "Tema",
    settingsLanguage = "Dil",
    settingsDark = "Garanky",
    settingsLight = "Açyk",
    settingsObject = "Obýekt",
    settingsSite = "Site",
    settingsRole = "Rol",
)

val EnStrings = AppStrings(
    authSubtitle = "Workforce Mobile",
    authUsername = "Username",
    authPassword = "Password",
    authLogin = "Sign In",
    authError = "Invalid credentials",
    authInfo = "Set credentials in Admin Panel → Workers → Key icon",
    all = "All",
    noData = "No data",
    loading = "Loading...",
    logout = "Sign Out",
    settings = "Settings",
    notifications = "Notifications",
    cancel = "Cancel",
    save = "Save",
    confirm = "Confirm",
    search = "Search...",
    refresh = "Refresh",
    tabDashboard = "Dashboard",
    tabBrigades = "Brigades",
    tabAttendance = "Attendance",
    tabOvertime = "Overtime",
    tabApprovals = "Approvals",
    tabReports = "Reports",
    statusPending = "Pending",
    statusSeen = "Seen",
    statusApproved = "Approved",
    statusRejected = "Rejected",
    workersPresent = "Present",
    workersAbsent = "Absent",
    workersTotal = "Total workers",
    shiftDay = "Day",
    shiftNight = "Night",
    shiftNone = "No shift",
    overtimeNewRequest = "+ New Request",
    overtimeSelectSiteChief = "Site Chief *",
    overtimeWorkDate = "Work date",
    overtimeNote = "Reason (optional)",
    overtimeSelectWorkers = "Select workers",
    overtimeSend = "Submit",
    overtimeBack = "← Back",
    notifNoItems = "No notifications",
    notifLateTitle = "workers not arrived",
    notifMissingTitle = "workers missing checkout",
    notifAddNote = "Add note",
    notifNoteExists = "Note added",
    notifSaveNote = "Save",
    notifNoteHint = "e.g. lost card, health issue...",
    notifNoEntry = "No entry",
    notifNoExit = "No exit",
    notifWorkedFor = "at work",
    brigMyWorkers = "My Workers",
    brigAddWorkers = "Add Workers",
    brigNoWorkers = "No workers",
    brigNoWorkersHint = "Add workers from the Add Workers tab.",
    brigRelease = "Remove worker",
    brigReleaseConfirm = "remove from your list?",
    brigAddDay = "Add Day",
    brigAddNight = "Add Night",
    brigAllAssigned = "All workers assigned",
    settingsTheme = "Theme",
    settingsLanguage = "Language",
    settingsDark = "Dark",
    settingsLight = "Light",
    settingsObject = "Object",
    settingsSite = "Site",
    settingsRole = "Role",
)

val RuStrings = AppStrings(
    authSubtitle = "Управление персоналом",
    authUsername = "Логин",
    authPassword = "Пароль",
    authLogin = "Войти",
    authError = "Неверные данные",
    authInfo = "Данные для входа задаются в Admin Panel → Workers → значок ключа",
    all = "Все",
    noData = "Нет данных",
    loading = "Загрузка...",
    logout = "Выйти",
    settings = "Настройки",
    notifications = "Уведомления",
    cancel = "Отмена",
    save = "Сохранить",
    confirm = "Подтвердить",
    search = "Поиск...",
    refresh = "Обновить",
    tabDashboard = "Дашборд",
    tabBrigades = "Бригады",
    tabAttendance = "Явка",
    tabOvertime = "Сверхурочные",
    tabApprovals = "Согласование",
    tabReports = "Отчёты",
    statusPending = "Ожидает",
    statusSeen = "Просмотрено",
    statusApproved = "Одобрено",
    statusRejected = "Отклонено",
    workersPresent = "Присутствуют",
    workersAbsent = "Отсутствуют",
    workersTotal = "Всего",
    shiftDay = "Дневная",
    shiftNight = "Ночная",
    shiftNone = "Без смены",
    overtimeNewRequest = "+ Новый запрос",
    overtimeSelectSiteChief = "Site Chief *",
    overtimeWorkDate = "Дата работы",
    overtimeNote = "Причина (необязательно)",
    overtimeSelectWorkers = "Выбрать работников",
    overtimeSend = "Отправить",
    overtimeBack = "← Назад",
    notifNoItems = "Нет уведомлений",
    notifLateTitle = "работников не пришли",
    notifMissingTitle = "работников без выхода",
    notifAddNote = "Добавить причину",
    notifNoteExists = "Причина добавлена",
    notifSaveNote = "Сохранить",
    notifNoteHint = "Напр: потерял карту, состояние здоровья...",
    notifNoEntry = "Нет входа",
    notifNoExit = "Нет выхода",
    notifWorkedFor = "на работе",
    brigMyWorkers = "Мои работники",
    brigAddWorkers = "Добавить",
    brigNoWorkers = "Нет работников",
    brigNoWorkersHint = "Добавьте работников на вкладке «Добавить».",
    brigRelease = "Убрать работника",
    brigReleaseConfirm = "убрать из списка?",
    brigAddDay = "Добавить (день)",
    brigAddNight = "Добавить (ночь)",
    brigAllAssigned = "Все работники закреплены",
    settingsTheme = "Тема",
    settingsLanguage = "Язык",
    settingsDark = "Тёмная",
    settingsLight = "Светлая",
    settingsObject = "Объект",
    settingsSite = "Площадка",
    settingsRole = "Роль",
)

fun getStrings(lang: Language): AppStrings = when (lang) {
    Language.TK -> TkStrings
    Language.EN -> EnStrings
    Language.RU -> RuStrings
}

val LocalStrings = staticCompositionLocalOf { RuStrings }
